### ISSUE TITLE
Selectively connect to cameras

### ISSUE THREAD

**Issue by JonnySme** [basler/pypylon#95] opened 2019-03-20 13:17 UTC
Hello! Can you please tell. I use several cameras that connect to the router. How can I connect a specific camera? I now use "CreateFirstDevice" and can only connect to the first camera. How can you selectively connect to any of the connected cameras, for example, if you use the "DeviceID" parameter.

Regards.

**Comment by Knoose** [comment] 2019-03-20 19:56
For IP cameras, I'm using: https://github.com/StudentCV/PyPylon/issues/13

**Comment by thiesmoeller** [comment] 2020-12-01 12:04
Duplicate of #63

**Closed by thiesmoeller** 2020-12-01 12:04 UTC
