### ISSUE TITLE
Installation issue for Linux and pylon 6.1

### ISSUE THREAD

**Issue by tomasBjornfot** [basler/pypylon#223] opened 2020-04-16 12:23 UTC
In the setup.py file (line 536) the path is set to opt/pylon5/ but for pylon 6.1, the folder name is just pylon.

**Comment by Merwanski** [comment] 2020-05-14 08:50
Yes this one did solve my issue :) 
Thank you @tomasBjornfot

**Comment by thiesmoeller** [comment] 2020-12-01 12:06
Duplicate of #296

**Closed by thiesmoeller** 2020-12-01 12:06 UTC
